### ISSUE TITLE
avro installation failed

### ISSUE THREAD

**Issue by r1y4n** [maateen/avro#103]
i followed the steps to install avro from this link: https://github.com/sarim/ibus-avro/issues/102

after executing the command `ibus restart` i found the following message:
`(ibus-daemon:7610): GLib-WARNING **: GChildWatchSource: Exit status of a child process was requested but ECHILD was received by waitpid(). Most likely the process is ignoring SIGCHLD, or some other thread is invoking waitpid() with a nonpositive first argument; either behavior can break applications that use g_child_watch_add()/g_spawn_sync() either directly or indirectly.
/usr/share/ibus-table/engine/main.py:27: PyGIWarning: IBus was imported without specifying a version first. Use gi.require_version('IBus', '1.0') before import to ensure that the right version gets loaded.
  from gi.repository import IBus
`
how to get rid of this? 
TIA
##

**Comment by maateen** [comment]
Is the Avro working? Also please specify your system spec.

**Comment by r1y4n** [comment]
after installation Avro does not show any error but in text entry settings Avro didn't appear. 

i am using Ubunutu 16.04 LTS.

**Comment by maateen** [comment]
What is the output of `ibus restart`?

**Comment by AnupamMitra** [comment]
I set up a new PC with Ubuntu 16.04. But this time Avro couldn't be installed like earlier occasions. I followed the procedure as per the link sarim#102. No error is reported after installation. Language Support shows Keyboard Input Method System Ibus. But in Text Entry Settings Avro did not appear.

**Comment by maateen** [comment]
@AnupamMitra Let's play some commands on terminal.

```
sudo apt purge ibus libibus-1.0-dev gjs ibus-1.0 gir1.2-ibus-1.0 -y
reboot
```

After that, follow this guide: [Avro Documentation](http://lab.maateen.me/avro/)

And keep me updated about the issue, please.

**Comment by AnupamMitra** [comment]
Thank you for your support. Yesterday night I applied your above suggestions but Avro couldn't be installed. Thereafter I reinstalled Ubuntu 16.04 and this time I only followed the guide Avro Documentation but in Text Entry Settings Avro yet to appear.

**Comment by maateen** [comment]
So, still you can't write in Avro?

**Comment by AnupamMitra** [comment]
Yes please.

**Comment by AnupamMitra** [comment]
@maateen Awaiting for your further suggestions.

**Comment by maateen** [comment]
Very soon we are gonna release a new version of Avro. Hope the problem will be resolved then.

**Comment by AnupamMitra** [comment]
Welcome. Thanks.

**Comment by AnupamMitra** [comment]
@maateen Did you release the new version of Avro which would be compatible with Ubuntu 16.04?

**Comment by maateen** [comment]
Till now not yet. That's under testing till now. Once I'm ready, I'll let
you know.

**Comment by AnupamMitra** [comment]
Okay,thanks.

**Comment by sadatia** [comment]
Not working in ElementeryOS Loki

**Comment by maateen** [comment]
@sadatia Actually the avro team is working on the new version. Once it has been released, these issues will be resolved, we hope.

**Comment by sadatia** [comment]
Looking forward

**Comment by AnupamMitra** [comment]
আমিও খুবই আগ্রহের সাথে অপেক্ষা করে আছি কবে উবুন্টু ১৬.০৪ -এ অভ্র ব্যবহার করতে পারবো। সত্যি কথা বলতে কি কম্পিউটারে বাংলায় কোনো কাজই করতে পারছিনা!

**Comment by maateen** [comment]
We'll let you know.
