### ISSUE TITLE
IBUS AVRO IN UBUNTU 16.04

### ISSUE THREAD

**Issue by AnupamMitra** [maateen/avro#104]
I have adopted the procedure to install IBus Avro in my laptop with O/S Ubuntu 16.04. But IBus Avro is not visible in Text Entry to choose. Need your expertise support. 
##

**Comment by maateen** [comment]
Can you please follow this solution: https://bn.maateen.me/install-avro-keyboard-in-ubuntu/

**Comment by AnupamMitra** [comment]
I have gone through the above solution provided by you and adopted all the steps described therein. But in the Text Entry Avro Phonetic is yet to be seen as Input Source. Please guide.

**Comment by maateen** [comment]
Let me check it again.

**Comment by AnupamMitra** [comment]
উবুন্টু ১৬.০৪ আমরা যারা ব্যবহার করি তারা কি আর অভ্র দিয়ে বাংলায় লিখতে পারবে না?

**Comment by maateen** [comment]
Off course, you can. Here is the new installation method: https://github.com/maateen/avro#ubuntu-1404-1604-1610-1704-1710-3264-bit
About Google Chrome issue, make sure, you are using the latest version.

**Comment by AnupamMitra** [comment]
This time again I faced with similar situation. In the Text Entry, Avro Phonetic is yet to be seen as Input Source.

**Comment by AnupamMitra** [comment]
মাতিন ভাই, আমার আগের জবাবটিকে অগ্রাহ্য করুন। Text Entry তে অভ্র ফোনেটিক কে আমারই খুঁজে পেতে ভুল হয়েছিল। আমি দুঃখিত। আবার পাশাপাশি আনন্দিতও বটে। অনেকদিন পর আবার লিনাক্স -এ অভ্র দিয়ে টাইপ করতে পারছি। আপনাকে অশেষ ধন্যবাদ। সালাম।

**Comment by maateen** [comment]
উচ্চারণটা মাটিন হবে। :) আপনাকেও সালাম।
