### ISSUE TITLE
IBus Avro not working in kubuntu 16.04.1

### ISSUE THREAD

**Issue by zaki-chowdhury** [maateen/avro#105]
I have installed ibus avro followed this method from here: https://maateen.me/install-avro-keyboard-in-ubuntu-16-04-lts/
 my installation is ok. haven't face any problem.But when active this keyboard and try to type in bangla it doesn't work. I followed every suggestion i found like removing 'autocorrect.js' file, updating i bus engine to latest version, even reinstalled it several time , but no luck.

**Comment by maateen** [comment]
If you ever upgrade the ibus engine to latest version, then avro won't never work. Perhaps, many people is getting this issues now-a-days. It may occur due to the latest changes in packages. I will suggest you to move to Probhat.

**Comment by zaki-chowdhury** [comment]
thanks for reply. :)
