### ISSUE TITLE
Avro isn't working in Linux Mint 18.1 Cinnamon x64

### ISSUE THREAD

**Issue by awolad** [maateen/avro#106]
>> By default Ibus not installed in Linux Mint. So I have installed it first following command:  **sudo apt-get install ibus**
>> Then I have selected **Ibus** from Settings > Languages > Input method drop down.
>> And finally after clicking **+** from  Settings > Keyboard > Layout, couldn't find bengali (avro) or avro like this.

Please can you help me to solve this issue.

**Comment by maateen** [comment]
It seems that you are not following our doc. Please follow it first. The issue isn't connected to us if you don't follow our guideline. Thanks.

**Comment by awolad** [comment]
I had successfully installed it on my Ubuntu pc according to avro doc from facebook. But it's not working by same procedure in Linux Mint though it's also debian based. Can you please test this for other debian based OS?

**Comment by maateen** [comment]
I have tested it. But It seems may be you are following the wrong doc. Remove all the versions of ibus from your PC. Then follow this doc: http://lab.maateen.me/avro/

**Comment by shafi-** [comment]
After following http://lab.maateen.me/avro doc linux mint 18.2 cinnamon not showing "IBus" in input method list. 
However, from terminal I got that "ibus" is not installed in my system. Then from terminal I installed ibus [ it installed ibus (1.5.11-1ubuntu2) ]. Now "IBus" is available as input method. But still avro or Bengali(avro) not showing in keyboard settings as said in the link above. 
Now what to do is, in the settings there is a "IBus preference". Go there and avro is there as input method. Configure IBus preference as you need. Then restart ibus [ it may not be required - I restarted without testing prior ]. How open your text editor and press the hot-key. 
"অভিনন্দন  আপনাকে"।

Maateen vai, please check this. 
There is a problem, it inserts a space just before the word. যেমনঃ লিখতে চাই "আমার"  তখন  হয়ে  যাচ্ছে " আমার" ।
