### ISSUE TITLE
avro keyboard problem in ubuntu 16.04

### ISSUE THREAD

**Issue by tanvir44665** [maateen/avro#110]
Hello,
recently I have upgraded my ubuntu 14.04 LTS to 16.04.After installing when I am trying text on facebook in bengali I found my avro layout is not working properly.So I reinstall it .But after 3 failed attempt it stiil is not working.Most often I can type my first word but for second after type letter the suggestion box baceme vanished and nothing came on the screen.None of the the key was working there.for continuing I have to escape from the text tab of fb and reload it. Please help . :-) 
Thanks for your patience.

**Comment by maateen** [comment]
Please, dive into the README section and follow our new instruction. Then come back and let us know. We are always with you.

**Comment by tanvir44665** [comment]
where will I find readme?

**Comment by maateen** [comment]
Please check here: https://github.com/maateen/avro/blob/master/README.md

**Comment by tanvir44665** [comment]
I followed all the instructuction as in READ ME.But I have to face the same problem still :'-(

**Comment by maateen** [comment]
Then please wait for our new version.

**Comment by AsifulNobel** [comment]
It seems the same problem persists. How long till the new version comes out?

**Comment by maateen** [comment]
Hello everyone! This problem should be fixed. Here is the solution: https://bn.maateen.me/install-avro-keyboard-in-ubuntu/

And the new version needs more time to be released. We hope your patience.
