### ISSUE TITLE
Avro not works in Elementary OS

### ISSUE THREAD

**Issue by susmitmohan** [maateen/avro#111]
I tried many times. I followed all the instructions, but too much disappointed for not getting this lovely avro. :( :( Only the .dev file installs properly but after that cannot choose Ibus though I rebooted my PC and also tried many ways. :(
Please do something for Elementary OS. My version is 0.4.0 (latest version) and 64bit.
It would be very pleasure for all Elementary OS users who love this avro. 
Many many thanks in advance.

**Comment by maateen** [comment]
Can you please try this: https://bn.maateen.me/install-avro-keyboard-in-ubuntu/ and let me know the update.

**Comment by maateen** [comment]
At this fork of Avro, we provide support only for Ubuntu.
