### ISSUE TITLE
IBus set_cursor_pos Error

### ISSUE THREAD

**Issue by maateen** [maateen/avro#32]
<a href="https://github.com/omicronlab"><img src="https://avatars.githubusercontent.com/u/423287?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [omicronlab](https://github.com/omicronlab)**
_Saturday Jul 21, 2012 at 10:04 GMT_
_Originally opened as https://github.com/sarim/ibus-avro/issues/32_

---

The following error occurred at least twice in `Kubuntu 12.04` & `Fedora 17` during testing and caused IBus to crash.

```
IBUS:ERROR:ibuslookuptable.c:323:ibus_lookup_table_set_cursor_pos: assertion failed: (cursor_pos < table->candidates->len)
```

Might be  an IBus bug, but deserves another check.
##

**Comment by ugcoder** [comment]
<a href="https://github.com/omicronlab"><img src="https://avatars.githubusercontent.com/u/423287?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [omicronlab](https://github.com/omicronlab)**
_Saturday Jul 21, 2012 at 10:58 GMT_

----

Another, may be related error from `Fedora 17`:

    IBUS:ERROR:candidatearea.c:361:candidate_area_set_candidates: assertion failed: (_tmp4__length1 < 16)
