### ISSUE TITLE
Building ibus-avro in CentOS 6.2 x86_64

### ISSUE THREAD

**Issue by maateen** [maateen/avro#33]
<a href="https://github.com/aftnix"><img src="https://avatars.githubusercontent.com/u/1655398?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [aftnix](https://github.com/aftnix)**
_Monday Jul 23, 2012 at 12:48 GMT_
_Originally opened as https://github.com/sarim/ibus-avro/issues/33_

---

First,

centos, epel, rpmfusion, rpmforge ...nothing seems to provide the requirements given for building ibus-avro. I have cloned ibus from its github repo. 

But configuring ibus in centos halts with this :

Requested 'glib-2.0 >= 2.26.0' but version of GLib is 2.22.5

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables GLIB2_CFLAGS
and GLIB2_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.

But it does not seem reasonable to update my gnome libraries manually and risk breaking my existing gnome apps. So Any previous version of ibus exists to which ibus-avro is compatible?

git tag only shows 1 "1.0" tag. Sow i'm doubting of any previous stable version. Still, CentOS is a production level distro, and used by many of us who do linux platform development. If its compatible with centos then it would be very nice.
##

**Comment by ugcoder** [comment]
<a href="https://github.com/sarim"><img src="https://avatars.githubusercontent.com/u/1235888?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [sarim](https://github.com/sarim)**
_Monday Jul 23, 2012 at 13:19 GMT_

----

Which version of ibus did you try to compile ? Avro need atleast ibus 1.4.1, or ibus 1.4.0 with this patch applied 
```    --- ibus/src/ibusengine.c.orig
    +++ ibus/src/ibusengine.c
    @@ -330,7 +330,7 @@ ibus_engine_class_init (IBusEngineClass
                 G_TYPE_FROM_CLASS (gobject_class),
                 G_SIGNAL_RUN_LAST,
                 G_STRUCT_OFFSET (IBusEngineClass, process_key_event),
    -            NULL, NULL,
    +            g_signal_accumulator_true_handled, NULL,
                 _ibus_marshal_BOOL__UINT_UINT_UINT,
                 G_TYPE_BOOLEAN,
                 3,```

link : https://github.com/ibus/ibus/commit/d3610308ed0d1d722de061d3957dcef55bcf7448
Ibus download link : http://code.google.com/p/ibus/downloads/list

Avro also needs gjs and gobject-introspection version 1.32, glib-2.0 version 2.32 to work properly.

So without updating your system, i dont think its possible to run ibus-avro. 
Server focused distros like centos,redhat always used old packages for stability.

With gjs 1.30, ibus-avro will partially work. You may be interested to try that.

**Comment by ugcoder** [comment]
<a href="https://github.com/aftnix"><img src="https://avatars.githubusercontent.com/u/1655398?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [aftnix](https://github.com/aftnix)**
_Monday Jul 23, 2012 at 21:35 GMT_

----


On Jul 23, 2012, at 8:19 PM, Sarim Khan wrote:

> Which version of ibus did you try to compile ? Avro need atleast  
> ibus 1.4.1, or ibus 1.4.0 with this patch applied
> ```    --- ibus/src/ibusengine.c.orig
>    +++ ibus/src/ibusengine.c
>    @@ -330,7 +330,7 @@ ibus_engine_class_init (IBusEngineClass
>                 G_TYPE_FROM_CLASS (gobject_class),
>                 G_SIGNAL_RUN_LAST,
>                 G_STRUCT_OFFSET (IBusEngineClass, process_key_event),
>    -            NULL, NULL,
>    +            g_signal_accumulator_true_handled, NULL,
>                 _ibus_marshal_BOOL__UINT_UINT_UINT,
>                 G_TYPE_BOOLEAN,
>                 3,```
>
> link : https://github.com/ibus/ibus/commit/d3610308ed0d1d722de061d3957dcef55bcf7448

The latest from github. I've not checked the version TAG.

>
> Avro also needs gjs and gobject-introspection version 1.32, glib-2.0  
> version 2.32 to work properly.
>

I can get these from sources i guess. But building a new glib may  
break my current gtk apps. I will try this in spare VM to see if it  
works. I will post results.
