### ISSUE TITLE
Can't write "পঙ্‌ক্তি" in Libreoffice

### ISSUE THREAD

**Issue by maateen** [maateen/avro#38]
<a href="https://github.com/shaquille19"><img src="https://avatars.githubusercontent.com/u/1734590?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [shaquille19](https://github.com/shaquille19)**
_Friday Nov 16, 2012 at 05:39 GMT_
_Originally opened as https://github.com/sarim/ibus-avro/issues/38_

---

I can't write পঙ্‌ক্তি in libreoffice using Ibus-Avro Phonetic. It' becoming পঙ্ক্তি। It's okay in here while I typing but problematic in Libreoffice. Can you please give a look at it?
##

**Comment by ugcoder** [comment]
<a href="https://github.com/sarim"><img src="https://avatars.githubusercontent.com/u/1235888?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [sarim](https://github.com/sarim)**
_Friday Nov 16, 2012 at 05:43 GMT_

----

let me know the key sequence you are using for "পঙ্‌ক্তি"

**Comment by ugcoder** [comment]
<a href="https://github.com/shaquille19"><img src="https://avatars.githubusercontent.com/u/1734590?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [shaquille19](https://github.com/shaquille19)**
_Friday Nov 16, 2012 at 05:45 GMT_

----

poNg,,kti
