### ISSUE TITLE
Cant type Bangla though avro enabled !

### ISSUE THREAD

**Issue by maateen** [maateen/avro#39]
<a href="https://github.com/sufibd2010"><img src="https://avatars.githubusercontent.com/u/2999835?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [sufibd2010](https://github.com/sufibd2010)**
_Sunday Dec 09, 2012 at 06:04 GMT_
_Originally opened as https://github.com/sarim/ibus-avro/issues/39_

---

I cant type bangla but I enabled ibus-avro. when i installed it worked. but few days later it dont work .

it is in ubuntu 12.04

I reinstalled , but not work !!!

![Selection_009.png](https://f.cloud.github.com/assets/2999835/2232/3e832ff0-41c6-11e2-9cc3-af16ed6968af.png)

here is a screenshot !
##

**Comment by ugcoder** [comment]
<a href="https://github.com/sarim"><img src="https://avatars.githubusercontent.com/u/1235888?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [sarim](https://github.com/sarim)**
_Saturday Dec 15, 2012 at 07:28 GMT_

----

Try this command in terminal ```rm ~/.candidate-selections.json```

**Comment by ugcoder** [comment]
<a href="https://github.com/sarim"><img src="https://avatars.githubusercontent.com/u/1235888?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [sarim](https://github.com/sarim)**
_Saturday Dec 15, 2012 at 07:29 GMT_

----

It will reset your avro installation.

**Comment by ugcoder** [comment]
<a href="https://github.com/syfulsharif"><img src="https://avatars.githubusercontent.com/u/2669892?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [syfulsharif](https://github.com/syfulsharif)**
_Thursday Mar 28, 2013 at 14:57 GMT_

----

Sarim Vaiya, I have been facing exactly the same issue. Tried re-installing Avro, but did not work out, i also tried the above command in terminal but no sign of hope. Please help me. 
![avro failure](https://f.cloud.github.com/assets/2669892/313753/b2fb3d9a-97b7-11e2-9dea-64d4ae7a28d8.png)

**Comment by ugcoder** [comment]
<a href="https://github.com/Nabid"><img src="https://avatars.githubusercontent.com/u/4307574?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Nabid](https://github.com/Nabid)**
_Monday Dec 30, 2013 at 12:10 GMT_

----

Can not type in Bangla while avro is running.
OS: Ubuntu 12.04.2 LTS

<b>Tried this command:</b>
<code>rm ~/.candidate-selections.json</code>
<b>This exception is thrown:</b>
<code>rm: cannot remove `/root/.candidate-selections.json': No such file or directory</code>

<b>Debug result:</b>
<code>JS ERROR: !!!     message = '"this._candidateSelections is null"'
101 18 0
    JS ERROR: !!!   Exception was: TypeError: this._candidateSelections is null
    JS ERROR: !!!     lineNumber = '321'
    JS ERROR: !!!     fileName = '"/usr/share/ibus-avro/suggestionbuilder.js"'
    JS ERROR: !!!     stack = '"([object Object],[object Array])@/usr/share/ibus-avro/suggestionbuilder.js:321
([object Object],[object Array],"\u09B9\u09C7",[object Object])@/usr/share/ibus-avro/suggestionbuilder.js:295
("he")@/usr/share/ibus-avro/suggestionbuilder.js:514
updateCurrentSuggestions([object _private_IBus_Engine])@/usr/share/ibus-avro/main-gjs.js:270
([object _private_IBus_Engine],101,18,0)@/usr/share/ibus-avro/main-gjs.js:92
@/usr/share/ibus-avro/main-gjs.js:419
"'</code>

<b>Fixed KEYEXPIRED error</b>
<code>wget -q http://download.opensuse.org/repositories/home:/sarimkhan/xUbuntu_12.04/Release.key -O- | sudo apt-key add -</code>
it terminated successfully. <code>OK</code>
Updated the repo. But still not working.
Any suggestion to fix this issue?
Thank you.

**Comment by ugcoder** [comment]
<a href="https://github.com/Nabid"><img src="https://avatars.githubusercontent.com/u/4307574?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Nabid](https://github.com/Nabid)**
_Monday Dec 30, 2013 at 12:18 GMT_

----

Creating a new issue. Posted here because it was still open.

**Comment by ugcoder** [comment]
<a href="https://github.com/emnoor"><img src="https://avatars.githubusercontent.com/u/2104003?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [emnoor](https://github.com/emnoor)**
_Monday Dec 30, 2013 at 15:32 GMT_

----

You didn't have to create a new issue :|
Are you trying to remove the file as root!? Do it with normal user.
Alternatively you can do this: Open Home in nautilus and type Ctrl+H to show hidden files and delete the file `.candidate-selections.json`

**Comment by ugcoder** [comment]
<a href="https://github.com/sarim"><img src="https://avatars.githubusercontent.com/u/1235888?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [sarim](https://github.com/sarim)**
_Monday Dec 30, 2013 at 15:37 GMT_

----

Try to run the command as normal user. Seems like you are trying it as root.

**Comment by ugcoder** [comment]
<a href="https://github.com/Nabid"><img src="https://avatars.githubusercontent.com/u/4307574?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Nabid](https://github.com/Nabid)**
_Monday Dec 30, 2013 at 16:03 GMT_

----

Yes, I was trying as root. Well, did it as normal user. It's worked fine.
Thanks a lot for support. You should close this issue as well as duplicate issue #56.
