### ISSUE TITLE
Can't write bangla in MS Office 2007 installed under wine 1.5.23 using ibus avro

### ISSUE THREAD

**Issue by maateen** [maateen/avro#40]
<a href="https://github.com/rajibnill"><img src="https://avatars.githubusercontent.com/u/3627867?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [rajibnill](https://github.com/rajibnill)**
_Monday Feb 18, 2013 at 16:07 GMT_
_Originally opened as https://github.com/sarim/ibus-avro/issues/41_

---

Can't write bangla MS Office 2007 installed under wine 1.5.23 using ibus avro.

System: 
1. Mint 14
2. Wine 1.23
3. MS Office 2007 SP2
4. ibus Avro
5. Unicode fonts like : Bangla, nikosh, siyam rupali, suttonyOMJ, Bensen etc.

Problem details:
1. shows only text suggestion but nothing is writing by ibus. I tried with different bangla fonts. Nothing is written using ibus avro.
1. Sometimes ibus can write bangla but that time can't write "Zafolla" and other word like "kono"

Please see this image below:
![Screenshot from 2013-02-18 22:06:39](https://f.cloud.github.com/assets/3627867/167794/43b3845a-79e5-11e2-898c-c01ae1dd61d9.png)
##

**Comment by ugcoder** [comment]
<a href="https://github.com/rajibnill"><img src="https://avatars.githubusercontent.com/u/3627867?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [rajibnill](https://github.com/rajibnill)**
_Monday Feb 18, 2013 at 16:11 GMT_

----

I tried to write : র‍্যাব কোন  ! ( rab kono).
Here in GitHub I stil can't write "rab". But here i can write kono (কোন) using ibus avro.

Please see the image:
![Screenshot from 2013-02-18 22:10:21](https://f.cloud.github.com/assets/3627867/167819/c3627d00-79e5-11e2-9db3-61d83d93a98a.png)

**Comment by ugcoder** [comment]
<a href="https://github.com/rajibnill"><img src="https://avatars.githubusercontent.com/u/3627867?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [rajibnill](https://github.com/rajibnill)**
_Monday Feb 18, 2013 at 16:24 GMT_

----

text suggestion is showing the right word but ibus can't wite down that word properly.

see the image: 
![Screenshot from 2013-02-18 22:24:14](https://f.cloud.github.com/assets/3627867/167859/b25315ae-79e7-11e2-8fc0-416433561c7a.png)

**Comment by ugcoder** [comment]
<a href="https://github.com/sarim"><img src="https://avatars.githubusercontent.com/u/1235888?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [sarim](https://github.com/sarim)**
_Monday Feb 18, 2013 at 17:22 GMT_

----

about ms-office><wine thing, that is maybe a problem with ibus and wine. i have no idea about this. 
About writing rab, try r`Zab

**Comment by ugcoder** [comment]
<a href="https://github.com/rajibnill"><img src="https://avatars.githubusercontent.com/u/3627867?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [rajibnill](https://github.com/rajibnill)**
_Monday Feb 18, 2013 at 17:33 GMT_

----

see what happens: if I use r`Zab:

![Screenshot from 2013-02-18 23:32:55](https://f.cloud.github.com/assets/3627867/168128/594eecbc-79f1-11e2-98e7-fb0aefda1461.png)

**Comment by ugcoder** [comment]
<a href="https://github.com/rajibnill"><img src="https://avatars.githubusercontent.com/u/3627867?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [rajibnill](https://github.com/rajibnill)**
_Thursday Feb 28, 2013 at 11:25 GMT_

----

Do you not have any solution for the problem?
Sarim Vai!
I can't write rab in web, please see this picture:
![Screenshot from 2013-02-18 23:32:55](https://f.cloud.github.com/assets/3627867/168128/594eecbc-79f1-11e2-98e7-fb0aefda1461.png)

Not only rab i can't write may other words like: PROJOTNE

**Comment by ugcoder** [comment]
<a href="https://github.com/sarim"><img src="https://avatars.githubusercontent.com/u/1235888?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [sarim](https://github.com/sarim)**
_Sunday Mar 03, 2013 at 07:42 GMT_

----

Try these.
1) Use solaimanlipi or any unicode font from omicronlab.
2) to write র‍্যাব rZab
3) পর্যন্ত porjonto
