### ISSUE TITLE
language changes back to english in libre office

### ISSUE THREAD

**Issue by maateen** [maateen/avro#41]
<a href="https://github.com/ganeshdas"><img src="https://avatars.githubusercontent.com/u/4133920?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ganeshdas](https://github.com/ganeshdas)**
_Friday Apr 12, 2013 at 06:30 GMT_
_Originally opened as https://github.com/sarim/ibus-avro/issues/42_

---

Hi,
I have latest ibus-avro installed.
If my suggestion is on and I type "pro" then input method automatically changes back to english, but if I keep suggestion off, than its okay.

Plus, if suggestion is on then linux version of avro is much slower than windows version of avro, and one request please add a visible keyboard. so if some spelling can not be written we can at least use mouse to type them

Last issue is there is no way to type "assamese" language in ibus-avro, windows version has this feature bcoz in windows version we can click on assamese Ra to type it.

Thanks
##

**Comment by ugcoder** [comment]
<a href="https://github.com/sarim"><img src="https://avatars.githubusercontent.com/u/1235888?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [sarim](https://github.com/sarim)**
_Friday Apr 12, 2013 at 06:49 GMT_

----

what OS you are using ? and which DE ? (gnome,kde....)

**Comment by ugcoder** [comment]
<a href="https://github.com/ganeshdas"><img src="https://avatars.githubusercontent.com/u/4133920?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ganeshdas](https://github.com/ganeshdas)**
_Friday Apr 12, 2013 at 07:29 GMT_

----

Ubuntu 12.10 (Quantal Quetzal)
what is DE? i think it should be Gnome

I am using a desktop pc

Intel® Core™2 Duo CPU E7300 @ 2.66GHz × 2

On 4/12/13, Sarim Khan <notifications@github.com> wrote:
> what OS you are using ? and which DE ? (gnome,kde....)
>
> On Friday, April 12, 2013, ganeshdas wrote:
>
>> Hi,
>> I have latest ibus-avro installed.
>> If my suggestion is on and I type "pro" then input method automatically
>> changes back to english, but if I keep suggestion off, than its okay.
>>
>> Plus, if suggestion is on then linux version of avro is much slower than
>> windows version of avro, and one request please add a visible keyboard.
>> so
>> if some spelling can not be written we can at least use mouse to type
>> them
>>
>> Last issue is there is no way to type "assamese" language in ibus-avro,
>> windows version has this feature bcoz in windows version we can click on
>> assamese Ra to type it.
>>
>> Thanks
>>
>> —
>> Reply to this email directly or view it on
>> GitHub<https://github.com/sarim/ibus-avro/issues/42>
>> .
>>
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/sarim/ibus-avro/issues/42#issuecomment-16278293
>


-- 
Regards
Ganesh Das
Guwahati, India
