### ISSUE TITLE
ibus-avro does not  working on Fedora 19 Gnome

### ISSUE THREAD

**Issue by maateen** [maateen/avro#45]
<a href="https://github.com/titaschanda"><img src="https://avatars.githubusercontent.com/u/5068393?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [titaschanda](https://github.com/titaschanda)**
_Monday Jul 22, 2013 at 21:55 GMT_
_Originally opened as https://github.com/sarim/ibus-avro/issues/46_

---

Hello,
         I have installed ibus-avro by adding http://download.opensuse.org/repositories/home:sarimkhan/Fedora_18/home:sarimkhan.repo to my repository list. As ibus is already integrated in Gnome 3.8, I opened Region and Language Settings and added Avro phonetic as an input method. But whenever I change to this input method, bengali scripts are not showing, only english letters are getting typed. Please, help to overcome this situation.  
##

**Comment by ugcoder** [comment]
<a href="https://github.com/sarim"><img src="https://avatars.githubusercontent.com/u/1235888?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [sarim](https://github.com/sarim)**
_Monday Jul 22, 2013 at 22:58 GMT_

----

i'll try this on fedora 19 and update you :)
>
>

**Comment by ugcoder** [comment]
<a href="https://github.com/sridip123"><img src="https://avatars.githubusercontent.com/u/5179993?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [sridip123](https://github.com/sridip123)**
_Wednesday Aug 07, 2013 at 06:54 GMT_

----

Is there any update on the resolution to this problem?

**Comment by ugcoder** [comment]
<a href="https://github.com/sarim"><img src="https://avatars.githubusercontent.com/u/1235888?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [sarim](https://github.com/sarim)**
_Wednesday Aug 07, 2013 at 07:34 GMT_

----

yes. i have added a new repo for fedora 19. please try that.

2013/8/7, sridip123 <notifications@github.com>:

**Comment by ugcoder** [comment]
<a href="https://github.com/sridip123"><img src="https://avatars.githubusercontent.com/u/5179993?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [sridip123](https://github.com/sridip123)**
_Wednesday Aug 07, 2013 at 11:06 GMT_

----

Thanks for so quick turn-around! :)
Would you please write me a step-by-step guide as inscribed in the following page: http://linux.omicronlab.com/fedora_17.html as to how to install ibus-avro on Fedora 19 from scratch? It would be a great help!!!!

Thanks in advance! :)

**Comment by ugcoder** [comment]
<a href="https://github.com/sarim"><img src="https://avatars.githubusercontent.com/u/1235888?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [sarim](https://github.com/sarim)**
_Wednesday Aug 07, 2013 at 11:17 GMT_

----

Actually i've fixed the code and published the updated repo for fedora 19 weeks ago, but forgot to post update here.
I'll post a guide for fedora 19 in our site, but for now, Try these steps.

##Installation

Step 1: Become root

    sudo -s

or

    su 

Step 2: Add ibus-avro repository

    cd /etc/yum.repos.d/
    curl -L -O http://download.opensuse.org/repositories/home:sarimkhan/Fedora_19/home:sarimkhan.repo

Step 3: Install ibus-avro

    yum install ibus-avro

##Activating

Now goto http://forum.projanmo.com/topic42140.html. Read the whole post, then follow the ibus-avro section.

**Comment by ugcoder** [comment]
<a href="https://github.com/sridip123"><img src="https://avatars.githubusercontent.com/u/5179993?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [sridip123](https://github.com/sridip123)**
_Wednesday Aug 07, 2013 at 11:25 GMT_

----

cool..........thanks again :)
