### ISSUE TITLE
Ask anonymous usage data from users for better prediction in future

### ISSUE THREAD

**Issue by maateen** [maateen/avro#47]
<a href="https://github.com/ienzam"><img src="https://avatars.githubusercontent.com/u/607461?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ienzam](https://github.com/ienzam)**
_Tuesday Sep 10, 2013 at 15:31 GMT_
_Originally opened as https://github.com/sarim/ibus-avro/issues/48_

---

Avro has a large user base, and can take user data to make the prediction way better.

If the usage data can be collected then those can be used for mapping english to bangla.

This type of crowdsourcing will help a lot to make an spell checking also in the future.
##

**Comment by ugcoder** [comment]
<a href="https://github.com/apurbapaul0"><img src="https://avatars.githubusercontent.com/u/2610904?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [apurbapaul0](https://github.com/apurbapaul0)**
_Monday Sep 16, 2013 at 06:05 GMT_

----

I think it is a good suggestion if it is possible.

**Comment by ugcoder** [comment]
<a href="https://github.com/emnoor"><img src="https://avatars.githubusercontent.com/u/2104003?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [emnoor](https://github.com/emnoor)**
_Monday Sep 16, 2013 at 11:49 GMT_

----

But you know the "taklas" all around! This could possibly pollute the dictionary!

**Comment by ugcoder** [comment]
<a href="https://github.com/ienzam"><img src="https://avatars.githubusercontent.com/u/607461?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ienzam](https://github.com/ienzam)**
_Monday Sep 16, 2013 at 11:57 GMT_

----

We don't need to add all the words, most popular transliterations will be
added only and we can incorporate other measures like online voting , etc
when we will have the backend ready to receive the feedbacks.

--Regards
Enzam

**Comment by ugcoder** [comment]
<a href="https://github.com/sarim"><img src="https://avatars.githubusercontent.com/u/1235888?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [sarim](https://github.com/sarim)**
_Monday Sep 16, 2013 at 15:20 GMT_

----

we have some similiar idea. Lets see what we can do :)
