### ISSUE TITLE
Ibus-avro repository cannot be added in Linux Mint 15 (KDE)

### ISSUE THREAD

**Issue by maateen** [maateen/avro#48]
<a href="https://github.com/navid-rida"><img src="https://avatars.githubusercontent.com/u/5724258?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [navid-rida](https://github.com/navid-rida)**
_Saturday Oct 19, 2013 at 09:13 GMT_
_Originally opened as https://github.com/sarim/ibus-avro/issues/49_

---

I tried to install ibus-avro in Linux mint 15 (KDE). I used the following command in my terminal to add ibus-avro repository :

sudo add-apt-repository "deb http://download.opensuse.org/repositories/home:/sarimkhan/xUbuntu_13.04/ ./"

But after entering this command, I got the following error:

Cannot add PPA: 'No JSON object could be decoded'.

I've also tried to add the PPA using the software sources menu which produces the same error. how can I fix this?
##

**Comment by ugcoder** [comment]
<a href="https://github.com/emnoor"><img src="https://avatars.githubusercontent.com/u/2104003?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [emnoor](https://github.com/emnoor)**
_Sunday Oct 20, 2013 at 17:28 GMT_

----

https://help.ubuntu.com/community/Repositories/CommandLine
