### ISSUE TITLE
how can i install avro in manjaro ?

### ISSUE THREAD

**Issue by maateen** [maateen/avro#50]
<a href="https://github.com/ghost"><img src="https://avatars.githubusercontent.com/u/10137?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ghost](https://github.com/ghost)**
_Tuesday Oct 29, 2013 at 07:52 GMT_
_Originally opened as https://github.com/sarim/ibus-avro/issues/51_

---

how can i install avro in manjaro ?
##

**Comment by ugcoder** [comment]
<a href="https://github.com/ghost"><img src="https://avatars.githubusercontent.com/u/10137?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ghost](https://github.com/ghost)**
_Monday Nov 11, 2013 at 18:21 GMT_

----

please anyone help :(

**Comment by ugcoder** [comment]
<a href="https://github.com/apandada1"><img src="https://avatars.githubusercontent.com/u/3063132?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [apandada1](https://github.com/apandada1)**
_Tuesday Nov 12, 2013 at 03:32 GMT_

----

Try these compiling instructions. https://github.com/sarim/ibus-avro#installation

**Comment by ugcoder** [comment]
<a href="https://github.com/ghost"><img src="https://avatars.githubusercontent.com/u/10137?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ghost](https://github.com/ghost)**
_Tuesday Nov 12, 2013 at 07:46 GMT_

----

it doesn't work for me :( some package not installing :'(

**Comment by ugcoder** [comment]
<a href="https://github.com/ghost"><img src="https://avatars.githubusercontent.com/u/10137?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ghost](https://github.com/ghost)**
_Tuesday Nov 12, 2013 at 07:47 GMT_

----

please test it on manjaro.

**Comment by ugcoder** [comment]
<a href="https://github.com/apandada1"><img src="https://avatars.githubusercontent.com/u/3063132?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [apandada1](https://github.com/apandada1)**
_Tuesday Nov 12, 2013 at 11:10 GMT_

----

Which packages are not installing?

**Comment by joymia** [comment]
Aur package system automatically installs the ibus avro
you have to enable it first
