### ISSUE TITLE
need support for arch linux

### ISSUE THREAD

**Issue by maateen** [maateen/avro#52]
<a href="https://github.com/ghost"><img src="https://avatars.githubusercontent.com/u/10137?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ghost](https://github.com/ghost)**
_Tuesday Nov 12, 2013 at 07:41 GMT_
_Originally opened as https://github.com/sarim/ibus-avro/issues/53_

---

hi, i use manjaro (based on arch). unfortunately there is no system to write bangla :( how can i install avro on manjaro ?
##

**Comment by ugcoder** [comment]
<a href="https://github.com/albabar"><img src="https://avatars.githubusercontent.com/u/4969617?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [albabar](https://github.com/albabar)**
_Thursday Apr 17, 2014 at 07:48 GMT_

----

Try this AUR pack: https://github.com/hjr265/arch-ibus-avro

**Comment by Pavel-Sayekat** [comment]
I am trying parabola-arch and downloaded the source, noticed that it is now in java (not in python) and the "./configure" results in ./configure
./configure: line 1667: syntax error near unexpected token `ibus-avro,'
./configure: line 1667: `AM_INIT_AUTOMAKE(ibus-avro, 1.0)'
