### ISSUE TITLE
Can't write bengali in Texmaker or Kile using avro

### ISSUE THREAD

**Issue by maateen** [maateen/avro#53]
<a href="https://github.com/mxant"><img src="https://avatars.githubusercontent.com/u/1019597?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mxant](https://github.com/mxant)**
_Saturday Dec 14, 2013 at 16:52 GMT_
_Originally opened as https://github.com/sarim/ibus-avro/issues/54_

---

First of all I want to thank you guys for these great software avro. I installed it in ubuntu 12.04 as described here(http://linux.omicronlab.com/ubuntu_12.04.html). It is working fine for editing tool eg gedit,libreoffice or web service eg facebook. But somehow it is not writing anything in case of kile of texmaker. All the softwares are latest updated. Could you please look into the matter? Thanks.
##

**Comment by ugcoder** [comment]
<a href="https://github.com/sarim"><img src="https://avatars.githubusercontent.com/u/1235888?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [sarim](https://github.com/sarim)**
_Sunday Dec 15, 2013 at 14:15 GMT_

----

try

    sudo apt-get install ibus-qt4

Logout, Login. See if that solves the issue.

**Comment by ugcoder** [comment]
<a href="https://github.com/mxant"><img src="https://avatars.githubusercontent.com/u/1019597?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mxant](https://github.com/mxant)**
_Wednesday Dec 18, 2013 at 05:18 GMT_

----

Thanks for the reply. I installed ibus-qt4. Its not helping. For every other editing software, it is showing prediction list(some of the words as a vertical list). But for kile/texmaker that prediction list is also not coming.
