### ISSUE TITLE
Not working in Fedora 20

### ISSUE THREAD

**Issue by maateen** [maateen/avro#54]
<a href="https://github.com/sphCow"><img src="https://avatars.githubusercontent.com/u/6238183?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [sphCow](https://github.com/sphCow)**
_Saturday Dec 21, 2013 at 20:31 GMT_
_Originally opened as https://github.com/sarim/ibus-avro/issues/55_

---

Avro was working fine in Fedora 19. I did a upgrade to Fedora 20 using the fedup tool. Everything is fine except Avro. It still types in English even after switching the keyboard layout to "Bengali (Avro Phonetic)". Bengali fonts are appearing but I can't tpe in Bengali even after switching the layout. 
##

**Comment by ugcoder** [comment]
<a href="https://github.com/sarim"><img src="https://avatars.githubusercontent.com/u/1235888?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [sarim](https://github.com/sarim)**
_Sunday Dec 22, 2013 at 09:33 GMT_

----

     /usr/bin/env gjs --include-path=/usr/share/ibus-avro /usr/share/ibus-avro/main-gjs.js

Try to run this in terminal and paste the output here.

**Comment by ugcoder** [comment]
<a href="https://github.com/sphCow"><img src="https://avatars.githubusercontent.com/u/6238183?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [sphCow](https://github.com/sphCow)**
_Sunday Dec 22, 2013 at 16:44 GMT_

----

What I'm getting is:
 <code>
/usr/bin/env gjs --include-path=/usr/share/ibus-avro /usr/share/ibus-avro/main-gjs.js
** Message: JS WARNING: [/usr/share/ibus-avro/main-gjs.js 57]: in strict mode code, functions may be declared only at top level or immediately within another function
** Message: JS WARNING: [/usr/share/ibus-avro/main-gjs.js 224]: in strict mode code, functions may be declared only at top level or immediately within another function
** Message: JS WARNING: [/usr/share/ibus-avro/main-gjs.js 238]: in strict mode code, functions may be declared only at top level or immediately within another function
** Message: JS WARNING: [/usr/share/ibus-avro/main-gjs.js 257]: in strict mode code, functions may be declared only at top level or immediately within another function
** Message: JS WARNING: [/usr/share/ibus-avro/main-gjs.js 269]: in strict mode code, functions may be declared only at top level or immediately within another function
** Message: JS WARNING: [/usr/share/ibus-avro/main-gjs.js 278]: in strict mode code, functions may be declared only at top level or immediately within another function
** Message: JS WARNING: [/usr/share/ibus-avro/main-gjs.js 301]: in strict mode code, functions may be declared only at top level or immediately within another function
** Message: JS WARNING: [/usr/share/ibus-avro/main-gjs.js 313]: in strict mode code, functions may be declared only at top level or immediately within another function
** Message: JS WARNING: [/usr/share/ibus-avro/main-gjs.js 324]: in strict mode code, functions may be declared only at top level or immediately within another function
** Message: JS WARNING: [/usr/share/ibus-avro/main-gjs.js 336]: in strict mode code, functions may be declared only at top level or immediately within another function
** Message: JS WARNING: [/usr/share/ibus-avro/main-gjs.js 346]: in strict mode code, functions may be declared only at top level or immediately within another function
** Message: JS WARNING: [/usr/share/ibus-avro/main-gjs.js 39]: assignment to undeclared variable exec_by_ibus
</code>

**Comment by ugcoder** [comment]
<a href="https://github.com/sphCow"><img src="https://avatars.githubusercontent.com/u/6238183?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [sphCow](https://github.com/sphCow)**
_Sunday Dec 22, 2013 at 17:26 GMT_

----

Another point to add:
The same problem persists with fresh install of FC20 (i.e. not upgraded using fedup/yum) also.

**Comment by ugcoder** [comment]
<a href="https://github.com/sphCow"><img src="https://avatars.githubusercontent.com/u/6238183?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [sphCow](https://github.com/sphCow)**
_Wednesday Jan 15, 2014 at 17:42 GMT_

----

Any fix?

**Comment by ugcoder** [comment]
<a href="https://github.com/sumankundu"><img src="https://avatars.githubusercontent.com/u/6561342?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [sumankundu](https://github.com/sumankundu)**
_Friday Aug 22, 2014 at 07:46 GMT_

----

I dont know whether you got the fix or not. For me too, after update, it stopped working. Today I got time and do the following to fix it.

First I downloded the source code. Then isntall, 
(1) sudo yum install libibus* 
(2) sudo yum install automake autoconf 
(3) ibus were updated with (1)
(4) Logged into the root using su
(5) Follow the command for installation in to document, i.e., 		
                aclocal && autoconf && automake --add-missing
		./configure --prefix=/usr
		sudo make install
(6) restarted the ibus

Now it is working with libre office and other text editors.
আশা করি কাজে লাগবে।

**Comment by ugcoder** [comment]
<a href="https://github.com/khanmrhasan"><img src="https://avatars.githubusercontent.com/u/8725547?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [khanmrhasan](https://github.com/khanmrhasan)**
_Thursday Mar 26, 2015 at 15:53 GMT_

----

@sumankundu , can you pls elaborate no. (3) i.e //(3) ibus were updated with (1)// ?

I am new to Fedora so can u pls mention the exact command(s) to perform this ?
