### ISSUE TITLE
Cannot install on 14.04 (Trusty)

### ISSUE THREAD

**Issue by maateen** [maateen/avro#56]
<a href="https://github.com/jahirju30"><img src="https://avatars.githubusercontent.com/u/6572074?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jahirju30](https://github.com/jahirju30)**
_Monday Feb 03, 2014 at 06:28 GMT_
_Originally opened as https://github.com/sarim/ibus-avro/issues/57_

---

I didn't find a Ubuntu 14.04 version of Avro. Tried to install 12.04 and 13.10, but don't work. 
##

**Comment by ugcoder** [comment]
<a href="https://github.com/nadimtuhin"><img src="https://avatars.githubusercontent.com/u/3125771?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [nadimtuhin](https://github.com/nadimtuhin)**
_Friday Jul 04, 2014 at 09:28 GMT_

----

I am down without avro on 14.04 :(

**Comment by ugcoder** [comment]
<a href="https://github.com/ediamin"><img src="https://avatars.githubusercontent.com/u/1541774?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ediamin](https://github.com/ediamin)**
_Friday Jul 04, 2014 at 09:49 GMT_

----

Here is the iBus-Avro installation guide for Ubuntu 14.04 http://linux.omicronlab.com/ubuntu_14.04.html

**Comment by ugcoder** [comment]
<a href="https://github.com/JHShovon"><img src="https://avatars.githubusercontent.com/u/8205394?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [JHShovon](https://github.com/JHShovon)**
_Saturday Jul 19, 2014 at 00:02 GMT_

----

Avro can not be install in ubuntu 14.04 LTS edition, but works well in13.10. Please, fix it.

I use this command:

sudo add-apt-repository "deb http://download.opensuse.org/repositories/home:/sarimkhan/xUbuntu_14.04/ ./"

wget -q http://download.opensuse.org/repositories/home:/sarimkhan/xUbuntu_14.04/Release.key -O- | sudo apt-key add -

sudo apt-get update

sudo apt-get install ibus-avro-trusty.

**Comment by ugcoder** [comment]
<a href="https://github.com/ssi-anik"><img src="https://avatars.githubusercontent.com/u/2676602?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ssi-anik](https://github.com/ssi-anik)**
_Thursday Mar 10, 2016 at 20:10 GMT_

----

@JHShovon Yes, I've followed those steps. But, Avro Phonetic is not shown on text entry input source.
![screenshot from 2016-03-11 02 08 52](https://cloud.githubusercontent.com/assets/2676602/13682948/5644665c-e72e-11e5-92f2-3f07efb09d9e.png)
