### ISSUE TITLE
avro problem in linux mint 16 kde

### ISSUE THREAD

**Issue by maateen** [maateen/avro#57]
<a href="https://github.com/salehahmed985"><img src="https://avatars.githubusercontent.com/u/5338221?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [salehahmed985](https://github.com/salehahmed985)**
_Saturday Feb 08, 2014 at 16:22 GMT_
_Originally opened as https://github.com/sarim/ibus-avro/issues/58_

---

মিন্ট ১৬ কেডিইতে ibus-avro ইন্সটল দেবার পর গুগল ক্রম, ফায়ারফক্সে কিংবা লিব্রেঅফিসে বাংলা আসে না। কিন্তু টেক্সট এডিটরে বাংলা আসে। 
##

**Comment by ugcoder** [comment]
<a href="https://github.com/sarim"><img src="https://avatars.githubusercontent.com/u/1235888?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [sarim](https://github.com/sarim)**
_Saturday Feb 08, 2014 at 16:25 GMT_

----

Trying installing ibus-qt4

    sudo apt-get install ibus-qt4

**Comment by ugcoder** [comment]
<a href="https://github.com/salehahmed985"><img src="https://avatars.githubusercontent.com/u/5338221?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [salehahmed985](https://github.com/salehahmed985)**
_Saturday Feb 08, 2014 at 16:38 GMT_

----

did not work brother. :(

**Comment by ugcoder** [comment]
<a href="https://github.com/salehahmed985"><img src="https://avatars.githubusercontent.com/u/5338221?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [salehahmed985](https://github.com/salehahmed985)**
_Monday Feb 10, 2014 at 09:22 GMT_

----

after installing ibus-gtk it worked.
