### ISSUE TITLE
Problem with duplicate words

### ISSUE THREAD

**Issue by maateen** [maateen/avro#64]
<a href="https://github.com/musaffa"><img src="https://avatars.githubusercontent.com/u/294616?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [musaffa](https://github.com/musaffa)**
_Monday Jun 02, 2014 at 11:57 GMT_
_Originally opened as https://github.com/sarim/ibus-avro/issues/65_

---

I'm using 14.04 64 bit with a fresh installation. When I press space button while writing a word, sometimes it creates a duplicate word for it. For example, while writing `আমি ভাল` I press space button it may become `আমি ভাল ভাল`. It has nothing to do with the word `ভাল` as it creates duplicate for any word. This duplicate word problem occurs very frequently in Trusty. It wasn't an issue in Ubuntu 13.10.
##

**Comment by ugcoder** [comment]
<a href="https://github.com/apurbapaul0"><img src="https://avatars.githubusercontent.com/u/2610904?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [apurbapaul0](https://github.com/apurbapaul0)**
_Friday Aug 01, 2014 at 07:00 GMT_

----

I also got same kind of problem some time. I am using Ubuntu 14.04 Gnome remix 64bit.

**Comment by ugcoder** [comment]
<a href="https://github.com/musaffa"><img src="https://avatars.githubusercontent.com/u/294616?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [musaffa](https://github.com/musaffa)**
_Sunday Aug 17, 2014 at 14:18 GMT_

----

I'm experiencing this issue only on the chromium browser.
