### ISSUE TITLE
Not working in ubuntu 14.04 64 bit

### ISSUE THREAD

**Issue by maateen** [maateen/avro#65]
<a href="https://github.com/shaonmostafiz"><img src="https://avatars.githubusercontent.com/u/4390553?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [shaonmostafiz](https://github.com/shaonmostafiz)**
_Sunday Jun 08, 2014 at 16:23 GMT_
_Originally opened as https://github.com/sarim/ibus-avro/issues/66_

---

Avro has been installed successfully and working fine for few days, but from last 2 days it is not working. I am not sure how to troubleshoot  the problem or what I have done to raised the problem. 
##

**Comment by ugcoder** [comment]
<a href="https://github.com/Solayman"><img src="https://avatars.githubusercontent.com/u/9523860?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Solayman](https://github.com/Solayman)**
_Monday Nov 03, 2014 at 03:26 GMT_

----

not working in ubuntu 14.04. while typing it dosen't convert to bangla
