### ISSUE TITLE
Font rendering problem in Kingoffice Linux

### ISSUE THREAD

**Issue by maateen** [maateen/avro#71]
<a href="https://github.com/shaquille19"><img src="https://avatars.githubusercontent.com/u/1734590?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [shaquille19](https://github.com/shaquille19)**
_Friday Aug 29, 2014 at 08:12 GMT_
_Originally opened as https://github.com/sarim/ibus-avro/issues/72_

---

Today I installed Kingoffice Linux version and tried to write Bangla using Avro. But it's problematic. When I tried to write "রহিম" it shows "রহমি"। Similiar is the case with other 'ই-কার' based words.
Any suggestion?
##

**Comment by ugcoder** [comment]
<a href="https://github.com/apandada1"><img src="https://avatars.githubusercontent.com/u/3063132?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [apandada1](https://github.com/apandada1)**
_Friday Aug 29, 2014 at 08:28 GMT_

----

Try writing the thing on LibbreOffice and paste it in Kingsoft Office. Check if it works.

**Comment by ugcoder** [comment]
<a href="https://github.com/shaquille19"><img src="https://avatars.githubusercontent.com/u/1734590?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [shaquille19](https://github.com/shaquille19)**
_Friday Aug 29, 2014 at 09:08 GMT_

----

I tried that but in vain.
