### ISSUE TITLE
can't install  ibus avro  

### ISSUE THREAD

**Issue by maateen** [maateen/avro#75]
<a href="https://github.com/sulaimanhaque"><img src="https://avatars.githubusercontent.com/u/9059051?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [sulaimanhaque](https://github.com/sulaimanhaque)**
_Thursday Oct 09, 2014 at 20:21 GMT_
_Originally opened as https://github.com/sarim/ibus-avro/issues/76_

---

 "sudo apt-get install ibus-avro-quantal " command is not working in my ubuntu 13.04 LTS  .
it says -
"Reading package lists... Done
Building dependency tree  
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 ibus-avro-quantal : Depends: gjs (>= 1.34.0-0ubuntu1) but it is not installable
                     Depends: gir1.2-ibus-1.0 but it is not installable
                     Depends: gir1.2-gtk-2.0 but it is not installable
E: Unable to correct problems, you have held broken packages."
##

**Comment by ugcoder** [comment]
<a href="https://github.com/sulaimanhaque"><img src="https://avatars.githubusercontent.com/u/9059051?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [sulaimanhaque](https://github.com/sulaimanhaque)**
_Friday Oct 10, 2014 at 20:34 GMT_

----

problem solved ! I've chosen best server from sofware and update ;
