### ISSUE TITLE
not working in ubuntu 14.04. i have install avro from official site. my installation is ok. havent face any problem. and last i add avro by sitting>keyboard>text entry>+> avro phonetic but when active this keyboard and try to type in bangla it dosen't work. please tell what should i do? 

### ISSUE THREAD

**Issue by maateen** [maateen/avro#78]
<a href="https://github.com/Solayman"><img src="https://avatars.githubusercontent.com/u/9523860?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Solayman](https://github.com/Solayman)**
_Monday Nov 03, 2014 at 03:35 GMT_
_Originally opened as https://github.com/sarim/ibus-avro/issues/79_

---
##

**Comment by ugcoder** [comment]
<a href="https://github.com/fa7ad"><img src="https://avatars.githubusercontent.com/u/7447677?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [fa7ad](https://github.com/fa7ad)**
_Sunday Jan 18, 2015 at 16:03 GMT_

----

Try to purge the package using.
 `apt-get purge ibus-avro-trusty`
and then re-installing it
 `apt-get install ibus-avro-trusty`
