### ISSUE TITLE
Space Button working slowly

### ISSUE THREAD

**Issue by maateen** [maateen/avro#79]
<a href="https://github.com/ohokbd"><img src="https://avatars.githubusercontent.com/u/10206483?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ohokbd](https://github.com/ohokbd)**
_Tuesday Dec 16, 2014 at 09:49 GMT_
_Originally opened as https://github.com/sarim/ibus-avro/issues/80_

---

১। উবুন্টু ১৪.১০ এ অভ্র ব্যাবহার করি। প্রতিবার অভ্র-->EN অথবা EN--> অভ্র তে সুইচ করলে NumLock অফ হয়ে যায়।
২। অভ্র তে স্পেস বাটন স্লো কাজ করছে। একটা ওয়ার্ড টাইপ করার পরে স্পেস দিয়ে আরেকটি ওয়ার্ড টাইপ করলে দুটো ওয়ার্ড সংযুক্ত হয়ে যাচ্ছে।
উদাহরণঃ ঠিকেরকম(ঠিক+space+এরকম) । এখানে ঠিক লেখার পরে একটু সময় পরে এরকম লিখতে হচ্ছে। তারাতারি টাইপ করতে গেলে স্পেস টা  আগে চলে আসে। 

Sorry ekhane bangla thik vabe lekha jacche na. See my screenshot.
![Uploading Screenshot from 2014-12-16 15:54:47.png . . .]()
##

**Comment by ugcoder** [comment]
<a href="https://github.com/apandada1"><img src="https://avatars.githubusercontent.com/u/3063132?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [apandada1](https://github.com/apandada1)**
_Tuesday Dec 16, 2014 at 16:20 GMT_

----

Wait for some time until screenshot is fully uploaded!
