### ISSUE TITLE
Avro is not working

### ISSUE THREAD

**Issue by maateen** [maateen/avro#82]
<a href="https://github.com/turjoy"><img src="https://avatars.githubusercontent.com/u/6727845?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [turjoy](https://github.com/turjoy)**
_Saturday Jan 31, 2015 at 06:27 GMT_
_Originally opened as https://github.com/sarim/ibus-avro/issues/83_

---

I am using linux mint 17 cinammon edition. Installed avro, but there is no interface of avro.
##

**Comment by ugcoder** [comment]
<a href="https://github.com/fa7ad"><img src="https://avatars.githubusercontent.com/u/7447677?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [fa7ad](https://github.com/fa7ad)**
_Thursday Mar 05, 2015 at 22:44 GMT_

----

run `ibus-setup` and `im-tool` then restart. it will probably be fixed. I remember using avro last time i ran LM
