### ISSUE TITLE
Unmet Dependencies (Elementary OS Luna)

### ISSUE THREAD

**Issue by maateen** [maateen/avro#85]
<a href="https://github.com/ykbks"><img src="https://avatars.githubusercontent.com/u/5730399?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ykbks](https://github.com/ykbks)**
_Monday Mar 23, 2015 at 06:46 GMT_
_Originally opened as https://github.com/sarim/ibus-avro/issues/86_

---

Hello there! Thank you so much for this awesome piece of software. It has changed the way we use Bangla for the better.

I have a small problem though, I cannot seem to be install it on my Elementary OS Luna (Ubuntu 14.10 based). Here's what it says:

![Image](http://i.imgur.com/dhZ1zeZ.png)

Any idea how to resolve this?
Thank you in advance!
##

**Comment by ugcoder** [comment]
<a href="https://github.com/sarim"><img src="https://avatars.githubusercontent.com/u/1235888?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [sarim](https://github.com/sarim)**
_Monday Mar 23, 2015 at 07:11 GMT_

----

try `sudo apt-get install ibus-avro-quantal`

**Comment by ugcoder** [comment]
<a href="https://github.com/ykbks"><img src="https://avatars.githubusercontent.com/u/5730399?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ykbks](https://github.com/ykbks)**
_Monday Mar 23, 2015 at 07:14 GMT_

----

Thank you for your reply.
Sadly, I end up on the same place. It seems the installation is trying to
download some components that already exist in a higher version than what
it wants to download.

**Comment by ugcoder** [comment]
<a href="https://github.com/sarim"><img src="https://avatars.githubusercontent.com/u/1235888?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [sarim](https://github.com/sarim)**
_Monday Mar 23, 2015 at 07:36 GMT_

----

What is the exact version of your elementary os? from wiki it says Elementary os luna is based on ubuntu 12.10, not 14.10

**Comment by ugcoder** [comment]
<a href="https://github.com/ykbks"><img src="https://avatars.githubusercontent.com/u/5730399?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ykbks](https://github.com/ykbks)**
_Monday Mar 23, 2015 at 14:12 GMT_

----

Yes. My bad. I have tried a few things and it seems other than the look and a few apps, I'm actually stuck with a very old version of Ubuntu. I am changing the OS for good.
Thank you again for the support.

**Comment by ugcoder** [comment]
<a href="https://github.com/apandada1"><img src="https://avatars.githubusercontent.com/u/3063132?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [apandada1](https://github.com/apandada1)**
_Tuesday Mar 24, 2015 at 03:01 GMT_

----

Luna is based on 12.04 LTS. So the original ibus-avro package is to be installed.
Try sudo apt-get install ibus-avro

The next version of Elementary OS (Freya) will be based on 14.04 LTS.
http://en.wikipedia.org/wiki/Elementary_OS#Versions
