### ISSUE TITLE
Using o between letters

### ISSUE THREAD

**Issue by maateen** [maateen/avro#88]
<a href="https://github.com/ssdtonoy"><img src="https://avatars.githubusercontent.com/u/11876917?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ssdtonoy](https://github.com/ssdtonoy)**
_Thursday Apr 09, 2015 at 20:10 GMT_
_Originally opened as https://github.com/sarim/ibus-avro/issues/89_

---

I have been facing a problem with the ibus-avro recently. Whenever I try to type a word with o in it, the characters change automatically to English and I have to revert back. But certain words are impossible to type in Bangla. For example, if I type "kono" I get কন। If I type "kOnO" then I sometimes get this "kOnO". It seems that there is a problem with the use of o between letters with ibus.
##

**Comment by ugcoder** [comment]
<a href="https://github.com/trjana49"><img src="https://avatars.githubusercontent.com/u/8972528?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [trjana49](https://github.com/trjana49)**
_Monday Jul 06, 2015 at 15:05 GMT_

----

You can read Avro Keyboard help file to write Bangla word and this will
help you to write bangla in ibus-avro.
