### ISSUE TITLE
Avro in Elementary OS Freya

### ISSUE THREAD

**Issue by maateen** [maateen/avro#91]
<a href="https://github.com/salehahmed985"><img src="https://avatars.githubusercontent.com/u/5338221?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [salehahmed985](https://github.com/salehahmed985)**
_Sunday Jul 05, 2015 at 19:31 GMT_
_Originally opened as https://github.com/sarim/ibus-avro/issues/92_

---

I could not install Avro in Elementary OS (Freya). I followed full instruction described in omicronlab's Ubuntu 14.04 page. I found no Avro option in keyboard layout setting. 
Thank you.
##

**Comment by ugcoder** [comment]
<a href="https://github.com/bivrantoshakil"><img src="https://avatars.githubusercontent.com/u/10580480?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [bivrantoshakil](https://github.com/bivrantoshakil)**
_Friday Aug 14, 2015 at 09:13 GMT_

----

Same Thing here. May Day! May Day!

**Comment by ugcoder** [comment]
<a href="https://github.com/tarique313"><img src="https://avatars.githubusercontent.com/u/2160924?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [tarique313](https://github.com/tarique313)**
_Friday Apr 22, 2016 at 06:02 GMT_

----

Please follow the steps instructed here: http://choyan.me/blog/elementary-os-avro/
